### ISSUE TITLE
请问有没有办法迁移到一台无法联网的机器上

### ISSUE THREAD

**Issue by EzioZz** [skoowoo/nvim-config#8]
我是在 mac 上安装了oh-my-nvim ，然后想在一台无法联网的机器上也安装这个。请问有什么思路吗？是不是把插件文件也复制过去就行了。

**Comment by skoowoo** [comment]
对，应该就是这个思路了，.config 目录下的 nvim 打包 copy 过去，理论上就可以了。我自己没有实操过，但我看别人这样做过。
